//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeCheques.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSXContabilidadSoap")]
    public interface WSXContabilidadSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SistemaDeCheques.ServiceReference1.HelloWorldResponse HelloWorld(SistemaDeCheques.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaDeCheques.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SistemaDeCheques.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Descripcion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarAsiento", ReplyAction="*")]
        SistemaDeCheques.ServiceReference1.registrarAsientoResponse registrarAsiento(SistemaDeCheques.ServiceReference1.registrarAsientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarAsiento", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaDeCheques.ServiceReference1.registrarAsientoResponse> registrarAsientoAsync(SistemaDeCheques.ServiceReference1.registrarAsientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SistemaDeCheques.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SistemaDeCheques.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaDeCheques.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SistemaDeCheques.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarAsientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarAsiento", Namespace="http://tempuri.org/", Order=0)]
        public SistemaDeCheques.ServiceReference1.registrarAsientoRequestBody Body;
        
        public registrarAsientoRequest() {
        }
        
        public registrarAsientoRequest(SistemaDeCheques.ServiceReference1.registrarAsientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarAsientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IdAuxiliar;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int CuentaDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CuentaCR;
        
        public registrarAsientoRequestBody() {
        }
        
        public registrarAsientoRequestBody(string Descripcion, int IdAuxiliar, double Monto, int CuentaDB, int CuentaCR) {
            this.Descripcion = Descripcion;
            this.IdAuxiliar = IdAuxiliar;
            this.Monto = Monto;
            this.CuentaDB = CuentaDB;
            this.CuentaCR = CuentaCR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarAsientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarAsientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaDeCheques.ServiceReference1.registrarAsientoResponseBody Body;
        
        public registrarAsientoResponse() {
        }
        
        public registrarAsientoResponse(SistemaDeCheques.ServiceReference1.registrarAsientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarAsientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int registrarAsientoResult;
        
        public registrarAsientoResponseBody() {
        }
        
        public registrarAsientoResponseBody(int registrarAsientoResult) {
            this.registrarAsientoResult = registrarAsientoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSXContabilidadSoapChannel : SistemaDeCheques.ServiceReference1.WSXContabilidadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSXContabilidadSoapClient : System.ServiceModel.ClientBase<SistemaDeCheques.ServiceReference1.WSXContabilidadSoap>, SistemaDeCheques.ServiceReference1.WSXContabilidadSoap {
        
        public WSXContabilidadSoapClient() {
        }
        
        public WSXContabilidadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSXContabilidadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSXContabilidadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSXContabilidadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaDeCheques.ServiceReference1.HelloWorldResponse SistemaDeCheques.ServiceReference1.WSXContabilidadSoap.HelloWorld(SistemaDeCheques.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SistemaDeCheques.ServiceReference1.HelloWorldRequest inValue = new SistemaDeCheques.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SistemaDeCheques.ServiceReference1.HelloWorldRequestBody();
            SistemaDeCheques.ServiceReference1.HelloWorldResponse retVal = ((SistemaDeCheques.ServiceReference1.WSXContabilidadSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaDeCheques.ServiceReference1.HelloWorldResponse> SistemaDeCheques.ServiceReference1.WSXContabilidadSoap.HelloWorldAsync(SistemaDeCheques.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaDeCheques.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SistemaDeCheques.ServiceReference1.HelloWorldRequest inValue = new SistemaDeCheques.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SistemaDeCheques.ServiceReference1.HelloWorldRequestBody();
            return ((SistemaDeCheques.ServiceReference1.WSXContabilidadSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaDeCheques.ServiceReference1.registrarAsientoResponse SistemaDeCheques.ServiceReference1.WSXContabilidadSoap.registrarAsiento(SistemaDeCheques.ServiceReference1.registrarAsientoRequest request) {
            return base.Channel.registrarAsiento(request);
        }
        
        public int registrarAsiento(string Descripcion, int IdAuxiliar, double Monto, int CuentaDB, int CuentaCR) {
            SistemaDeCheques.ServiceReference1.registrarAsientoRequest inValue = new SistemaDeCheques.ServiceReference1.registrarAsientoRequest();
            inValue.Body = new SistemaDeCheques.ServiceReference1.registrarAsientoRequestBody();
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.IdAuxiliar = IdAuxiliar;
            inValue.Body.Monto = Monto;
            inValue.Body.CuentaDB = CuentaDB;
            inValue.Body.CuentaCR = CuentaCR;
            SistemaDeCheques.ServiceReference1.registrarAsientoResponse retVal = ((SistemaDeCheques.ServiceReference1.WSXContabilidadSoap)(this)).registrarAsiento(inValue);
            return retVal.Body.registrarAsientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaDeCheques.ServiceReference1.registrarAsientoResponse> SistemaDeCheques.ServiceReference1.WSXContabilidadSoap.registrarAsientoAsync(SistemaDeCheques.ServiceReference1.registrarAsientoRequest request) {
            return base.Channel.registrarAsientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaDeCheques.ServiceReference1.registrarAsientoResponse> registrarAsientoAsync(string Descripcion, int IdAuxiliar, double Monto, int CuentaDB, int CuentaCR) {
            SistemaDeCheques.ServiceReference1.registrarAsientoRequest inValue = new SistemaDeCheques.ServiceReference1.registrarAsientoRequest();
            inValue.Body = new SistemaDeCheques.ServiceReference1.registrarAsientoRequestBody();
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.IdAuxiliar = IdAuxiliar;
            inValue.Body.Monto = Monto;
            inValue.Body.CuentaDB = CuentaDB;
            inValue.Body.CuentaCR = CuentaCR;
            return ((SistemaDeCheques.ServiceReference1.WSXContabilidadSoap)(this)).registrarAsientoAsync(inValue);
        }
    }
}
